// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJJ4P2outxQOXnatxUbffUDUl77Fcf11Y',
    appId: '1:213698548031:web:ace307e99144026808438a',
    messagingSenderId: '213698548031',
    projectId: 'calendar-sharing-634a4',
    authDomain: 'calendar-sharing-634a4.firebaseapp.com',
    storageBucket: 'calendar-sharing-634a4.appspot.com',
    measurementId: 'G-T54SYH2NW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGdPfqhFIZRdy-Y8-_QOJ072rSwnCTcxo',
    appId: '1:213698548031:android:fd95648c2410765208438a',
    messagingSenderId: '213698548031',
    projectId: 'calendar-sharing-634a4',
    storageBucket: 'calendar-sharing-634a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxFt_e0MjOYV18fAcek7J5LbpzG3OTvOg',
    appId: '1:213698548031:ios:5b520f97bb7d09ac08438a',
    messagingSenderId: '213698548031',
    projectId: 'calendar-sharing-634a4',
    storageBucket: 'calendar-sharing-634a4.appspot.com',
    iosBundleId: 'com.example.calendarSharing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxFt_e0MjOYV18fAcek7J5LbpzG3OTvOg',
    appId: '1:213698548031:ios:5b520f97bb7d09ac08438a',
    messagingSenderId: '213698548031',
    projectId: 'calendar-sharing-634a4',
    storageBucket: 'calendar-sharing-634a4.appspot.com',
    iosBundleId: 'com.example.calendarSharing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJJ4P2outxQOXnatxUbffUDUl77Fcf11Y',
    appId: '1:213698548031:web:e87a66d77731c8a708438a',
    messagingSenderId: '213698548031',
    projectId: 'calendar-sharing-634a4',
    authDomain: 'calendar-sharing-634a4.firebaseapp.com',
    storageBucket: 'calendar-sharing-634a4.appspot.com',
    measurementId: 'G-W1S3JBZD8Q',
  );
}
